# Generated by Django 4.1.1 on 2022-09-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название объкта')),
                ('type_o', models.CharField(max_length=30, verbose_name='Тип объкта')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс объкта')),
                ('season_date_open', models.DateTimeField(null=True, verbose_name='Сезонный день открытия')),
                ('season_date_close', models.DateTimeField(null=True, verbose_name='Сезонный день закрытия')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_view', models.CharField(max_length=20, verbose_name='Тип лица')),
                ('name', models.CharField(max_length=20, verbose_name='Имя владельца')),
                ('full_name_head', models.CharField(max_length=100, verbose_name='ФИО руководителя')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('opening_date', models.DateTimeField(verbose_name='День открытия')),
            ],
        ),
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата учета')),
                ('num_visit', models.PositiveIntegerField(verbose_name='Количество посетивших')),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objectmodel')),
            ],
        ),
        migrations.AddField(
            model_name='objectmodel',
            name='id_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.ownermodel'),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название мероприятия')),
                ('kind', models.CharField(max_length=50, verbose_name='Тип мероприятия')),
                ('date', models.DateTimeField(verbose_name='День мероприятия')),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objectmodel')),
            ],
        ),
    ]
