# Generated by Django 4.1.1 on 2022-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_objectmodel_season_date_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectmodel',
            name='num_seat',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество мест'),
        ),
    ]
