# Generated by Django 4.1.1 on 2022-09-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_objectmodel_num_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='id_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.ownermodel', verbose_name='Владелец'),
        ),
    ]
