# Generated by Django 4.1.1 on 2022-09-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_objectmodel_id_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objectmodel', verbose_name='Название объкта'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.objectmodel', verbose_name='Название объкта'),
        ),
    ]
