# Generated by Django 4.1.1 on 2022-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_eventmodel_id_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='season_date_close',
            field=models.DateField(blank=True, null=True, verbose_name='Сезонный день закрытия'),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='season_date_open',
            field=models.DateField(blank=True, null=True, verbose_name='Сезонный день открытия'),
        ),
    ]
