# Generated by Django 4.1.1 on 2022-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_objectmodel_season_date_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(verbose_name='День мероприятия'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='date',
            field=models.DateField(verbose_name='Дата учета'),
        ),
    ]
