# Generated by Django 4.1.1 on 2022-09-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_eventmodel_date_alter_visitmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermodel',
            name='opening_date',
            field=models.DateField(verbose_name='День открытия'),
        ),
    ]
