# Generated by Django 4.1.1 on 2022-09-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_alter_visitmodel_num_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermodel',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
