# Generated by Django 4.1.1 on 2022-09-29 14:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_alter_ownermodel_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermodel',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='BY', unique=True, verbose_name='Номер телефона'),
        ),
    ]
